# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vmv-zW3U7ogROQ82m7T4-fofwDv-lW1i
"""

pip install streamlit pandas matplotlib

# streamlit_app.py

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Title
st.title("📊 Simple Data Explorer")

# Upload CSV
uploaded_file = st.file_uploader("Upload a CSV file", type=["csv"])

if uploaded_file is not None:
    # Load the data
    df = pd.read_csv(uploaded_file)
    st.write("✅ Data Preview:")
    st.dataframe(df.head())

    # Select column for plotting
    numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns.tolist()

    if numeric_columns:
        col = st.selectbox("Choose a numeric column to plot", numeric_columns)

        # Plot
        fig, ax = plt.subplots()
        df[col].hist(bins=20, ax=ax)
        ax.set_title(f"Histogram of {col}")
        st.pyplot(fig)
    else:
        st.warning("No numeric columns found for plotting.")
else:
    st.info("Please upload a CSV file to proceed.")